### ISSUE TITLE
GFW_List没有谷歌规则

### ISSUE THREAD

**Issue by HuiMi24** [xinhugo/Free-List#2]
gfw_list没有谷歌相关的规则，是否可以考虑合并OmegaRules_List_GFW.sorl 和OmegaRules_List_Google.sorl

**Comment by xinhugo** [comment]
> gfw_list没有谷歌相关的规则，是否可以考虑合并OmegaRules_List_GFW.sorl和OmegaRules_List_Google.sorl

可以
